# Generated by Django 4.2.13 on 2024-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_stock_data_stock_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='share_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
